DROP TABLE EMP_BOARDS CASCADE CONSTRAINTS;

CREATE TABLE EMP_BOARDS (
	 ID NUMBER NOT NULL
	,TITLE VARCHAR2(100) NOT NULL
	,CONTENT VARCHAR2(2000)
	,EMPID NUMBER NOT NULL
	,CREATEDATE DATE DEFAULT(SYSDATE)
	,PRIMARY KEY EMP_BOARDS_ID_PK PRIMARY KEY (ID)
	,CONSTRAINT EMP_BOARDS_EMPID_FK FOREIGN KEY(EMPID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

