SELECT ROWNUM
	 , FIRST_NAME 
	 , LAST_NAME 
	 , SALARY 
	 , COMMISSION_PCT 
 FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
  AND ROWNUM <= 15
ORDER BY SALARY; 


SELECT  *
FROM (
SELECT FIRST_NAME
	 , LAST_NAME
	 , SALARY
	 , COMMISSION_PCT
  FROM EMPLOYEES 
 WHERE COMMISSION_PCT IS NOT NULL
 ORDER BY SALARY DESC
 )
 WHERE ROWNUM <= 15; --이미 서브쿼리에서 정렬된 순서에서 상위 15개까지만 조회하겠다는 의미가 된다.
 
 
WITH EMP_COM --빈번하게 사용되는 구분에 통으로 별칭 부여 (재사용성을 위함) 
 AS(SELECT FIRST_NAME
	 , LAST_NAME
	 , SALARY
	 , COMMISSION_PCT
  FROM EMPLOYEES 
 WHERE COMMISSION_PCT IS NOT NULL
 ORDER BY SALARY DESC)
SELECT * FROM EMP_COM 


SELECT FIRST_NAME
	 , LAST_NAME
	 , SALARY
	 , RANK() OVER(ORDER BY SALARY DESC) AS 순위
  FROM EMPLOYEES;
  
SELECT FIRST_NAME
	 , LAST_NAME
	 , SALARY
	 , DENSE_RANK() OVER(ORDER BY SALARY DESC) AS 순위
  FROM EMPLOYEES;
SELECT *
  FROM (SELECT FIRST_NAME
	 , LAST_NAME
	 , SALARY
	 , RANK() OVER(ORDER BY SALARY DESC) AS 순위
  FROM EMPLOYEES )
 WHERE 순위 <= 5;
 
-- Oracle 전용구문
SELECT *
  FROM EMPLOYEES E, DEPARTMENTS D
 WHERE E.DEPARTMENT_ID  = D.DEPARTMENT_ID ; 
 
--Ansi 표준구문(이거써라)

SELECT  *
  FROM EMPLOYEES E
  JOIN DEPARTMENTS D 
    ON E.DEPARTMENT_ID  = D.DEPARTMENT_ID;
    
SELECT  *
  FROM EMPLOYEES E
  JOIN DEPARTMENTS D USING(DEPARTMENT_ID); -- DPARTMENT_ID를 매개 로 합쳐라 

  -- 왼쪽 테이블 정보 기준으로 결합
SELECT *
  FROM EMPLOYEES E
  LEFT JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID  = D.DEPARTMENT_ID 
 WHERE E.EMPLOYEE_ID = 178;  
  
  -- 오른쪽 테이블 정보 기준으로 결합 
SELECT *
  FROM EMPLOYEES E
  RIGHT JOIN DEPARTMENTS D
     ON E.DEPARTMENT_ID  = D.DEPARTMENT_ID;
    
    
  -- 그냥 안겹치는 값도 양쪽 테이블에 속한거면 전부 표기  
SELECT *
  FROM EMPLOYEES E
  FULL JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID  = D.DEPARTMENT_ID; 
   
 --Oracle 전용구문  
   --LEFT OUTTER랑 같은코드
SELECT *
  FROM EMPLOYEES E, DEPARTMENTS D
 WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID(+);
  

  --RIGHT OUTTER랑 같은코드
SELECT *
  FROM EMPLOYEES E, DEPARTMENTS D
 WHERE E,DEPARTMENT_ID(+) = D.DEPARTMENT_ID;  

--카데시안 곱
SELECT COUNT(*)
  FROM EMPLOYEES 
 CROSS JOIN DEPARTMENTS;


SELECT X * Y AS TOTAL 
FROM (SELECT (SELECT COUNT(*) FROM EMPLOYEES) AS X
     , (SELECT COUNT(*) FROM DEPARTMENTS) AS Y
   FROM DUAL 
   );
 
SELECT *
  FROM JOBS;
  
SELECT * 
  FROM EMPLOYEES E
  JOIN JOBS J 
    ON (E.SALARY BETWEEN J.MIN_SALARY AND J.MAX_SALARY); --NON_EQU JOIN 넌 이콜 조인 (범위에 해당하면 조인시켜라)
    
SELECT * 
  FROM EMPLOYEES E1
  JOIN EMPLOYEES E2 
    ON E1.DEPARTMENT_ID = E2.DEPARTMENT_ID; -- 동일한 테이블 끼리 조인한 형식 = SELF JOIN (같은값끼리 합친것)    