CREATE TABLE EMP_COMMISSION
AS SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, COMMISSION_PCT 
FROM EMPLOYEES
WHERE 1 = 0;


CREATE TABLE EMP_NO_COMMISSION
AS SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE 1 = 0;

SELECT * FROM EMP_COMMISSION;
SELECT * FROM EMP_NO_COMMISSION;


INSERT INTO EMP_COMMISSION (
	   SELECT EMPLOYEE_ID
	        , FIRST_NAME
	        , LAST_NAME
	        , SALARY
	        , COMMISSION_PCT
	     FROM EMPLOYEES 
	    WHERE COMMISSION_PCT IS NOT NULL 
	    );