SELECT FIRST_NAME || ' ' || LAST_NAME AS 이름
	 , REPLACE(PHONE_NUMBER, '.', '-') AS 전화번호
	 , LOWER(EMAIL || '@example.com') AS 이메일 
	 , TO_CHAR(HIRE_DATE , 'YYYY"년" MM"월" DD"일"') AS 입사일
	 , FLOOR(SYSDATE - TO_DATE(HIRE_DATE)) AS 근무일
	 , TRUNC(SALARY * 1260 * (1 + NVL(COMMISSION_PCT, 0)), -3) AS 급여
FROM EMPLOYEES
ORDER BY HIRE_DATE ASC;


SELECT NVL(SUBSTR(PHONE_NUMBER, 1, 3), '총계') AS 회선번호
	 , COUNT(*) AS 회선수
FROM EMPLOYEES
GROUP BY ROLLUP(SUBSTR(PHONE_NUMBER, 1, 3));


SELECT MANAGER_ID AS 관리자ID
     , COUNT(EMPLOYEE_ID) AS "관리 직원수"
FROM EMPLOYEES
GROUP BY MANAGER_ID
HAVING MANAGER_ID IS NOT NULL;
