CREATE TABLE T_MYBATIS (
	   id NUMBER
	 , name VARCHAR2(100)
	 , today DATE
);

ALTER TABLE T_MYBATIS ADD CONSTRAINT T_MYBATIS_ID_PK PRIMARY KEY(ID); 

CREATE SEQUENCE SEQ_MYBATIS;

INSERT INTO T_MYBATIS  VALUES(SEQ_MYBATIS.NEXTVAL,

SELECT * FROM T_MYBATIS;
DELETE FROM T_MYBATIS;

SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME
	 , SALARY
  FROM EMPLOYEES
 WHERE SALARY >= 10000
   AND DEPARTMENT_ID IN (80, 90, 100); 
  


INSERT INTO T_MYBATIS VALUES(SEQ_MYBATIS.NEXTVAL, 'test', SYSDATE);
SELECT SEQ_MYBATIS.CURRVAL FROM DUAL;
SELECT * FROM T_MYBATIS WHERE ID = 89;
  
  
SELECT SEQ_MYBATIS.NEXTVAL FROM DUAL;
INSERT INTO T_MYBATIS VALUES(SEQ_MYBATIS.CURRVAL, 'test', SYSDATE);
SELECT * FROM T_MYBATIS WHERE ID = 89; 
 
  
  SELECT D.DEPARTMENT_NAME
  	   , COUNT(*) AS TOTAL
  	   , D.DEPARTMENT_ID 
	 	 FROM EMPLOYEES E JOIN DEPARTMENTS D 
	 	 ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
	 	 GROUP BY D.DEPARTMENT_NAME, D.DEPARTMENT_ID ;
	 	
	 	
  SELECT * FROM DEPARTMENTS;   
  SELECT * FROM EMPLOYEES ;   
