CREATE OR REPLACE FUNCTION FUNC_TEST1(v1 NUMBER) RETURN NUMBER 
IS BEGIN					--함수명   매개변수       반환타입 	
	RETURN v1 + 10;
END;

SELECT FUNC_TEST1(5) FROM DUAL;




CREATE OR REPLACE FUNCTION FUNC_TEST2(v1 VARCHAR2) RETURN VARCHAR2 
IS BEGIN					--함수명   매개변수       반환타입 	
	RETURN v1 || 'Done!!';
END;

SELECT FUNC_TEST2('Hello') FROM DUAL;




CREATE OR REPLACE FUNCTION FUNC_TEST3(v1 NUMBER ,v2 NUMBER) RETURN VARCHAR2 
IS							--함수명   매개변수       반환타입
	var VARCHAR2(10) := 'Done!!';
BEGIN					 	
	RETURN v1 + v2 || var;
END;

SELECT FUNC_TEST3(10, 20) FROM DUAL;