 CREATE TABLE accounts(
 	  userid	 VARCHAR2(20) PRIMARY KEY
 	, userpw	 VARCHAR2(20)
 	, username   VARCHAR2(20)
 	, gender	 CHAR(1)
 	, age		 NUMBER
 	, createdate DATE
 );

SELECT * FROM accounts;

DELETE FROM accounts;

DROP TABLE accounts;

SELECT * FROM EMPLOYEES; 
 


CREATE TABLE DEPARTMENT(
	DEPTCODE NUMBER PRIMARY KEY
	, DEPTNAME NVARCHAR2(10) NOT NULL
	, DEPTNO NUMBER
);

CREATE TABLE EMPLOYEE(
	EMPNO NUMBER PRIMARY KEY
	,EMPNAME VARCHAR2(10) NOT NULL
	,DEPTNO NUMBER REFERENCES DEPARTMENT(DEPTCODE)
 );

 DROP TABLE DEPARTMENT;
 DROP TABLE EMPLOYEE;
SELECT EMPNO
, EMPNAME
, DEPTNO
, DEPTNAME 
FROM EMPLOYEE
JOIN DEPARTMENT USING(DEPTNO);