CREATE TABLE my_exercise (
		idx                 NUMBER     PRIMARY KEY
	  ,	EVENT_NAME          VARCHAR2(20)  NOT NULL  
	  , SETS_NUMBER			NUMBER   	  NOT NULL  
	  , E_NUMBER			NUMBER   	  NOT NULL 
	  , P_TIME				VARCHAR2(10)
      , START_DATE   	    DATE 		  NOT NULL 
      , UPDATE_DATE         DATE		  NOT NULL 
);

CREATE TABLE PERMISSIONS (
		empId     NUMBER 
	  , tableName VARCHAR2(100)
	  , pRead     VARCHAR2(1) DEFAULT('N') CHECK(pRead IN('Y', 'N'))
	  , pAdd 	  VARCHAR2(1) DEFAULT('N') CHECK(pAdd IN('Y', 'N'))
	  , pUpdate   VARCHAR2(1) DEFAULT('N') CHECK(pUpdate IN('Y', 'N'))
	  , pDelete   VARCHAR2(1) DEFAULT('N') CHECK(pDelete IN('Y', 'N'))
	  , CONSTRAINT PERMISSIONS_EMPID_TABLENAME_PK PRIMARY KEY(empId, tableName)
);

INSERT INTO PERMISSIONS(empId, tableName)
SELECT  EMPLOYEE_ID AS empId
	 , 'employees' AS tableName
 FROM EMPLOYEES;
 
INSERT INTO PERMISSIONS(empId, tableName)
SELECT  EMPLOYEE_ID AS empId
	 , 'departments' AS tableName
 FROM EMPLOYEES;
 
INSERT INTO PERMISSIONS(empId, tableName)
SELECT  EMPLOYEE_ID AS empId
	 , 'locations' AS tableName
 FROM EMPLOYEES;
 
INSERT INTO PERMISSIONS(empId, tableName)
SELECT  EMPLOYEE_ID AS empId
	 , 'jobs' AS tableName
 FROM EMPLOYEES;
 
UPDATE PERMISSIONS 
 SET pRead = 'Y'
WHERE EMPID = 100
 AND TABLENAME IN ('departments');


SELECT * FROM PERMISSIONS;
SELECT * FROM EMPLOYEES;
SELECT * FROM JOBS;


CREATE TABLE EMPBOARDS (
		   , ID			 NUMBER	PRIMARY KEY
		   , TITLE		 VARCHAR2(100) NOT NULL 
		   , CONTENT	 VARCHAR2(2000)	
		   , EMPLOYEE_ID NUMBER FOREIGN KEY REFERENCES EMPLOYEES(EMPLOYEE_ID)
		   , CREATE_DATE DATE
);