
DECLARE
	TYPE TYPE_NAME_RECORD IS RECORD (
		ID			EMPLOYEES.EMPLOYEE_ID%TYPE
	  ,	FNAME		EMPLOYEES.FIRST_NAME%TYPE
	  , LNAME 	    EMPLOYEES.LAST_NAME%TYPE
	  , SALARY		EMPLOYEES.SALARY%TYPE
	  , DEPT_NAME   DEPARTMENTS.DEPARTMENT_NAME%TYPE
	);
	TYPE_RECORD   TYPE_NAME_RECORD;
BEGIN
	SELECT E.EMPLOYEE_ID
		 , E.FIRST_NAME
		 , E.LAST_NAME
		 , E.SALARY
		 , D.DEPARTMENT_NAME
		 INTO TYPE_RECORD
		FROM EMPLOYEES E JOIN DEPARTMENTS D 
		ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
		WHERE EMPLOYEE_ID = 100;
	DBMS_OUTPUT.PUT_LINE(TYPE_RECORD.ID);
	DBMS_OUTPUT.PUT_LINE(TYPE_RECORD.FNAME);
	DBMS_OUTPUT.PUT_LINE(TYPE_RECORD.LNAME);
	DBMS_OUTPUT.PUT_LINE(TYPE_RECORD.SALARY);
	DBMS_OUTPUT.PUT_LINE(TYPE_RECORD.DEPT_NAME);
END;


DECLARE
	TYPE NAME_TABLE_TYPE IS TABLE OF EMPLOYEES%ROWTYPE INDEX BY BINARY_INTEGER;
	DATA_TABLE   NAME_TABLE_TYPE;
	IDX NUMBER := 1;
BEGIN
	FOR D IN (SELECT * FROM EMPLOYEES) LOOP 
		DATA_TABLE(IDX) := D;
		IDX := IDX + 1;
	END LOOP;
	
	FOR I IN 1..DATA_TABLE.COUNT LOOP
		DBMS_OUTPUT.PUT_LINE(DATA_TABLE(I).EMPLOYEE_ID);
	END LOOP;
END;




